name: Package JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build and Test
      - name: Build and test
        run: mvn clean verify -DskipTests=false -DskipDocs=true

      # Package the JAR
      - name: Package the JAR
        if: success() # Only run if the tests were successful
        run: mvn package

      # Upload the JAR as an artifact with versioned name
      - name: Upload versioned JAR Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: tinytools-${{ steps.get_version.outputs.version }}-jar
          path: target/*.jar

      # Extract version from pom.xml
      - name: Get version
        id: get_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

